### ISSUE TITLE
DB_URL being overwritten

### ISSUE THREAD

**Issue by williamhuangh** [jfrog/artifactory-docker-examples#106]
setting up artifactory with the kubernetes yamls, I'm setting a couple env vars like this

```
env:
        - name: DB_TYPE
          value: postgresql
        - name: DB_USER
          value: artifactory_user
        - name: DB_PASSWORD
          value: artifactory_password
        - name: DB_URL
          value: jdbc:postgresql://MY_DB_URL:5432/artifactory_name
```
however, it seems like this gets overwritten in the copy to db.properties into
```
type=postgresql
driver=org.postgresql.Driver
url=jdbc:postgresql://postgresql:5432/artifactory_name
username=artifactory_user
password=artifactory_password
```
seems like it ignores the `MY_DB_URL` portion of the url. i've gone into the volume itself and manually fixed db.properties so that now has the right url, but this seems like a pretty big bug, unless im missing something here
