### ISSUE TITLE
Simplify Xray installation for seasoned admins

### ISSUE THREAD

**Issue by crazy-max** [jfrog/artifactory-docker-examples#115]
Hi,

> Originally created here [RTFACT-17455](https://www.jfrog.com/jira/browse/RTFACT-17455)

In our company we master Docker concepts. We already have an Artifactory instance deployed with Docker Swarm and we plan to move to Xray soon. However, installing Xray with Docker is done with a third party shell script which doesn't really suit us in our deployment infrastructure.

I noticed that @maheshjfrog has created an example configuration for the [OpenShift platform for Xray](https://github.com/jfrog/artifactory-docker-examples/tree/master/openshift/xray).
Would it be possible to also have a configuration example for Docker compose and Swarm?

I have started with something like that :

```yml
version: '2'

services:
  xray-server:
    image: docker.bintray.io/jfrog/xray-server:2.3.2
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - postgres
      - mongodb
    volumes:
      - ./xray:/var/opt/jfrog/xray/data
    environment:
      - XRAYCONFIGPATH=/var/opt/jfrog/xray/data
      - DOCKER_COMPOSE_FLAGS=
      - DOCKER_COMPOSE_XRAY_FLAGS=
    restart: always

  xray-indexer:
    image: docker.bintray.io/jfrog/xray-indexer:2.3.2
    ports:
      - 7002:7002
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./xray:/var/opt/jfrog/xray/data
    environment:
      - XRAYCONFIGPATH=/var/opt/jfrog/xray/data
      - DOCKER_COMPOSE_FLAGS=
      - DOCKER_COMPOSE_XRAY_FLAGS=
    restart: always

  xray-analysis:
    image: docker.bintray.io/jfrog/xray-analysis:2.3.2
    ports:
      - 7000:7000
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./xray:/var/opt/jfrog/xray/data
    environment:
      - XRAYCONFIGPATH=/var/opt/jfrog/xray/data
      - DOCKER_COMPOSE_FLAGS=
      - DOCKER_COMPOSE_XRAY_FLAGS=
    restart: always

  xray-persist:
    image: docker.bintray.io/jfrog/xray-persist:2.3.2
    ports:
      - 7003:7003
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./xray:/var/opt/jfrog/xray/data
    environment:
      - XRAYCONFIGPATH=/var/opt/jfrog/xray/data
      - DOCKER_COMPOSE_FLAGS=
      - DOCKER_COMPOSE_XRAY_FLAGS=
    restart: always

  rabbitmq:
    image: docker.bintray.io/jfrog/xray-rabbitmq:3.6.1-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always

  postgres:
    image: docker.bintray.io/jfrog/xray-postgres:9.5.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=xray
      - POSTGRES_PASSWORD=xray
      - POSTGRES_DB=xraydb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: docker.bintray.io/jfrog/xray-mongo:3.2.6
    entrypoint: /bin/bash -c "chmod 777 /data/logs; /entrypoint.sh --logpath /data/logs/xray-mongo.log --auth"
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - ./mongodb/logs:/data/logs
      - ./mongodb/configdb:/data/configdb
      - ./mongodb/db:/data/db
    restart: always
```
