### ISSUE TITLE
Postgress, Artifactory, and Nginx containers do not sync with local time.

### ISSUE THREAD

**Issue by schmidkyle** [jfrog/artifactory-docker-examples#179]
Can you add the following volume to each of the containers configuration with in docker-compose, so that it will sync with the local underline system?
 - "/etc/localtime:/etc/localtime:ro"
I have tested it on my system and it works, but I am using Ubuntu 18.04. I am not sure if it will work on all builds?

Here is what my configuration looks like when I make the change. 
```
version: '3'
services:
  postgresql:
    image: docker.bintray.io/postgres:9.6.11
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=${POSTGRES_PSWRD}
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
     - "/etc/localtime:/etc/localtime:ro"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.16.0
    container_name: artifactory
    ports:
     - 8081:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
     - "/etc/localtime:/etc/localtime:ro"
    environment:
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=${POSTGRES_PSWRD}
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:6.16.0
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory
    links:
     - artifactory
    volumes:
     - /data/nginx:/var/opt/jfrog/nginx
     - "/etc/localtime:/etc/localtime:ro"
    environment:
     - ART_BASE_URL=http://artifactory:8081/artifactory
     - SSL=true
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
```
