### ISSUE TITLE
Test Automation Using docker.bintray.io/jfrog/artifactory-oss Image

### ISSUE THREAD

**Issue by faraonc** [jfrog/artifactory-docker-examples#187]
I am writing a script to automate grooming our Artifactory. Due to some of the files are currently used for production, I want to test my script using `docker.bintray.io/jfrog/artifactory-oss` image. Is there a way to prevent Artifactory to force user `admin` to change password on initial startup?

Thanks!

**Comment by jamshid** [comment]
Yeah `docker.bintray.io/jfrog/artifactory-oss:4.16.1` was nice because it would automatically be configured for anonymous access and with a maven repo. Now with 6.17.0 I have to manually go to the http://DOCKER-HOST:8081 website and login initially as admin:password, change password to a long password, skip proxy server, Create the Maven repo, then go to Admin => Security Configuration => Allow anonymous.

**Comment by eldada** [comment]
@faraonc This is a general change for Artifactory. Not related to the Docker image.
Can you open an issue in [Artifactory's public JIRA](https://www.jfrog.com/jira)?

**Comment by faraonc** [comment]
> @faraonc This is a general change for Artifactory. Not related to the Docker image.
> Can you open an issue in [Artifactory's public JIRA](https://www.jfrog.com/jira)?

@eldada 
I think we pretty much abandon the test, so I am gonna let you determine if writing a JIRA ticket is still needed. 

It is important to note that most Docker images available like Postgres or MongoDB would have an entrypoint directory available to initialize the container in the proper state.

For example:
Note: `- ./db/postgres/sql_scripts/:/docker-entrypoint-initdb.d`
```yml
    postgres:
        image: postgres:12.1
        container_name: postgres
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/cert.pem -c ssl_key_file=/var/lib/postgresql/key.pem
        ports:
            - "${FS_PG_PORT:-5432}:${FS_PG_PORT:-5432}"
        environment:
            POSTGRES_USER: ${FS_PG_USER:-pgadmin}
            POSTGRES_PASSWORD: ${FS_PG_PWD:-pgpwd}
        volumes:
            - ./db/postgres/sql_scripts/:/docker-entrypoint-initdb.d
            - ./ca/cert.pem:/var/lib/postgresql/cert.pem
            - ./ca/key.pem:/var/lib/postgresql/key.pem
```
